spring.application.name=regclient_newVersion

# Server Configuration & Context Path
server.port=8080
server.servlet.context-path=/RegclientNewVersionApplication

# Local PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/voter_reg
#spring.datasource.username=postgres
#spring.datasource.password=Eagle@213
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/voter_reg
#spring.datasource.password=postgres
#spring.datasource.password=postgres

# PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/voter_reg
#spring.datasource.username=postgres
#spring.datasource.password=Eagle@213

#spring.datasource.driver-class-name=org.postgresql.Driver

# Workstation PostgreSQL Database Configuration
spring.datasource.url1=jdbc:postgresql://192.168.1.25:5432/voter_reg
spring.datasource.username1=postgres
spring.datasource.password1=Msp@321#

spring.datasource.url2=jdbc:postgresql://192.168.1.25:5432/applicants?currentSchema=public
spring.datasource.username2=postgres
spring.datasource.password2=Msp@321#
#Local applicants
spring.datasource.url3=jdbc:postgresql://localhost:5432/applicants?currentSchema=applicants
spring.datasource.username3=postgres
spring.datasource.password3=Eagle@213
# JPA / Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# =========================
# Primary DB
# =========================
app.datasource.primary.jdbc-url=jdbc:postgresql://localhost:5432/voter_reg
app.datasource.primary.username=postgres
app.datasource.primary.password=Eagle@213
app.datasource.primary.driver-class-name=org.postgresql.Driver

# =========================
# Secondary DB
# =========================
app.datasource.secondary.jdbc-url=jdbc:postgresql://localhost:5432/applicants
app.datasource.secondary.username=postgres
app.datasource.secondary.password=Eagle@213
app.datasource.secondary.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
