spring.application.name=regclient_newVersion

# Server Configuration & Context Path
server.port=8080
<<<<<<< Updated upstream
server.servlet.context-path=/RegclientNewVersionApplication

#spring.datasource.url=jdbc:postgresql://localhost:5432/voter_reg
#spring.datasource.password=postgres
spring.datasource.password=postgres

# PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/voter_reg
#spring.datasource.username=postgres
#spring.datasource.password=Eagle@213

=======
server.address=0.0.0.0
server.servlet.context-path=/RegclientNewVersionApplication

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/backup_votater
spring.datasource.username=postgres
spring.datasource.password=root
>>>>>>> Stashed changes
spring.datasource.driver-class-name=org.postgresql.Driver

# Workstation PostgreSQL Database Configuration
spring.datasource.url1=jdbc:postgresql://192.168.1.232:5432/voter_reg
spring.datasource.username1=postgres
spring.datasource.password1=Msp@321#

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

